### ISSUE TITLE
Plugin does not work well with "Workspace grid"

### ISSUE THREAD

**Issue by Michael-A-D** [sustmi/gnome-shell-extension-workspace-switcher-popup-thumbnails#1]
I wanted to use both this plugin and "Workspace grid", in order to have a 3x3 grid with preview. However, when I enable both and try to switch workspaces, previews are shown in a 9x1 vertical array, and the switcher is stuck (I can't close it, need to restart gnome).

It seems there is some kind of incompatibility because workspace-switcher-popup-thumbnails expects an array of workspaces, and not a grid.

**Comment by AllanDaemon** [comment]
I was creating an Arch Linux package for this plugin when I saw this. I need this plugin also because I use the workspace grid plugin, and with dozens (I use 5x5, or 6x6 grids sometimes), the lack of thumbnail become really bad, and so this extension is a lifesaver.

And I tested here and It happens the same thing: shows one vertical array in the left edge of the screen, and hangs the gnome shell.

**Comment by ruffsl** [comment]
I'm not too familiar with javascript, but where in the code do you suppose it's assuming a single column list structure, as opposed to a 2d array grid?

**Comment by sustmi** [comment]
I am sorry guys but I do not have time to debug and fix this issue. I personally do not use the extension so I do not even have any motivation to debug the issue. :(
Feel free to send a pull request (accepting it would not require so much time) or even fork the repository.
Thanks for understanding.

**Comment by sustmi** [comment]
I looked into it and I cannot find any reasonable way how to make these two extensions work together.

Both extensions use inheritance and extend `imports.ui.workspaceThumbnail.ThumbnailsBox` class and both completely replace some of it's methods with custom code.

The extensions would need to "extend" the original class by only adding new features directly into it (eg. by monkey patching) and not to overwrite any existing code (or at least not the parts that the other extension needs). But neither of the extensions adheres such non-conflict rules. :(

**Comment by sustmi** [comment]
Good news. If you want to combine this extension and "Workspace Grid" extension there is now "Workspace Matrix" extension that does exactly that: https://extensions.gnome.org/extension/1485/workspace-matrix/ .

It looks like "Workspace Grid" extension is currently not supported https://github.com/workspace-grid/workspace-grid/issues/119#issuecomment-484577950 so you may want to migrate to "Workspace Matrix" extension anyway.

I am closing this issue since it's not needed anymore to make this extension compatible with "Workspace Grid".
