### ISSUE TITLE
increase the size of the thumbnails

### ISSUE THREAD

**Issue by somethingGoneWrong** [sustmi/gnome-shell-extension-workspace-switcher-popup-thumbnails#5]
Is it possible to increase the size of the thumbnails?
maybe with settings like 2x, 3x, 4x? thx

**Comment by sustmi** [comment]
Hello. Sorry for late reply.
I tried to change the size of the thumbnails but it is really hard to do this from an extension. Unfortunately, it cannot be done simply such as through change in a CSS style.

There is a `MAX_THUMBNAIL_SCALE` variable that restricts the maximal size of thumbnails:
https://github.com/GNOME/gnome-shell/blob/7bb84dae805c98899ec3361b3c65cb0ebde9fb6c/js/ui/workspaceThumbnail.js#L15
It basically says that even if you have only 2 desktops, their thumbnail will never take more than 1/10 of you screen size. (If you have many desktops, they would be even smaller in order to fit on the screen.)

I did not manage to find out how to rewrite the variable from an extension. The only other way is to override three functions that use this variable and that will very likely break with a new version of GNOME Shell.

I am sorry but I do not have time to support such extension.

**Comment by sustmi** [comment]
Hi @somethingGoneWrong .
If you want bigger thumbnails, you can use "Workspace Matrix" extension that I just discovered: https://extensions.gnome.org/extension/1485/workspace-matrix/ .
It replaces "Workspace Switcher Popup with Thumbnails" and has the possibility to set "Scale of workspace thumbnails".
Note: If you do not need the workspace grid functionality, you can always set number of columns to one. ;)

I am closing this issue now since there is another extension that can do what you need.
